delete from categoria;
insert into categoria values(0,null,null);
insert into categoria values(1,'ARTE, ANTIGÜEDADES, RELOJES Y JOYAS',0);
insert into categoria values(2,'Antigüedades',1);
insert into categoria values(3,'Adornos de vitrina',2);
insert into categoria values(4,'Arqueología',2);
insert into categoria values(5,'Cerámica, lozas, porcelana',2);
insert into categoria values(6,'Escultura, Talla y Piedra',2);
insert into categoria values(7,'Láminas',2);
insert into categoria values(8,'Lamparas y Apliques',2);
insert into categoria values(9,'Mueble Español y Castellano',2);
insert into categoria values(10,'Muebles',2);
insert into categoria values(11,'Pinturas y Tapices',2);
insert into categoria values(12,'Plata y Estaños',2);
insert into categoria values(13,'Otros',2);
insert into categoria values(14,'Antigüedades y Arte Africano',1);
insert into categoria values(15,'Fetiches',14);
insert into categoria values(16,'Máscaras',14);
insert into categoria values(17,'Metales',14);
insert into categoria values(18,'Otros',14);
insert into categoria values(19,'Arte',1);
insert into categoria values(20,'Cuadros',19);
insert into categoria values(21,'Esculturas y bronces',19);
insert into categoria values(22,'Láminas y Grabados',19);
insert into categoria values(23,'Tauromaquia',19);
insert into categoria values(24,'Otros',19);
insert into categoria values(25,'Joyas',1);
insert into categoria values(26,'Relojes',1);
insert into categoria values(27,'Relojes antiguos',26);
insert into categoria values(28,'Relojes de colección',26);
insert into categoria values(29,'Relojes de lujo',26);
insert into categoria values(30,'Relojes de pared',26);
insert into categoria values(31,'Relojes de pulsera',26);
insert into categoria values(32,'Relojes modernos',26);
insert into categoria values(33,'AUDIO, VIDEO, FOTOGRAFIA Y TELEFONIA',0);
insert into categoria values(34,'Audio',33);
insert into categoria values(35,'Amplificadores',34);
insert into categoria values(36,'Cadenas Hi-Fi',34);
insert into categoria values(37,'Instrumentos música',34);
insert into categoria values(38,'Lectoras',34);
insert into categoria values(39,'Otros',34);
insert into categoria values(40,'Fotografía',33);
insert into categoria values(41,'Cámaras fotográficas',40);
insert into categoria values(42,'Lentes y objetivos',40);
insert into categoria values(43,'Otros',40);
insert into categoria values(44,'Telefonía',33);
insert into categoria values(45,'Accesorios de telefonía móvil',44);
insert into categoria values(46,'Teléfonos fijos',44);
insert into categoria values(47,'Teléfonos móviles',44);
insert into categoria values(48,'Otros',44);
insert into categoria values(49,'Video',33);
insert into categoria values(50,'Cámaras de video',49);
insert into categoria values(51,'Reproductores de video',49);
insert into categoria values(52,'Televisores',49);
insert into categoria values(53,'Otros',49);
insert into categoria values(54,'COLECCIONABLES',0);
insert into categoria values(55,'Abanicos',54);
insert into categoria values(56,'Armas',54);
insert into categoria values(57,'Bastones',54);
insert into categoria values(58,'Botellas',54);
insert into categoria values(59,'Licor',58);
insert into categoria values(60,'Miniaturas',58);
insert into categoria values(61,'Refrescos',58);
insert into categoria values(62,'Otros',58);
insert into categoria values(63,'Caretas y mascaras',54);
insert into categoria values(64,'Manuscritos y autógrafos',54);
insert into categoria values(65,'Militar',54);
insert into categoria values(66,'Minerales',54);
insert into categoria values(67,'Modelismo',54);
insert into categoria values(68,'Naipes',54);
insert into categoria values(69,'Objetos de escritorio y pisapapeles',54);
insert into categoria values(70,'Pins',54);
insert into categoria values(71,'Publicidad y artículos publicitarios',54);
insert into categoria values(72,'Tabaco y artículos para fumadores',54);
insert into categoria values(73,'Tarjetas Telefónicas de España',54);
insert into categoria values(74,'Distribución Pública',73);
insert into categoria values(75,'Promoción Privada',73);
insert into categoria values(76,'Otras Tarjetas',73);
insert into categoria values(77,'Tarjetas Telefónicas del Mundo',54);
insert into categoria values(78,'África',77);
insert into categoria values(79,'América',77);
insert into categoria values(80,'Asia',77);
insert into categoria values(81,'Europa',77);
insert into categoria values(82,'Otros',54);
insert into categoria values(83,'HARDWARE, SOFTWARE Y CONSOLAS',0);
insert into categoria values(84,'Apple',83);
insert into categoria values(85,'Hardware',84);
insert into categoria values(86,'Consolas y Juegos',83);
insert into categoria values(87,'Nintendo',86);
insert into categoria values(88,'Sega',86);
insert into categoria values(89,'Sony',86);
insert into categoria values(90,'Otros',86);
insert into categoria values(91,'Hardware PC',83);
insert into categoria values(92,'Cámaras digitales',91);
insert into categoria values(93,'Cpu´s',91);
insert into categoria values(94,'Discos Duros',91);
insert into categoria values(95,'Impresoras',91);
insert into categoria values(96,'Lectoras/Grabadoras CD-ROM',91);
insert into categoria values(97,'Lectoras/Grabadoras DVD',91);
insert into categoria values(98,'Memoria',91);
insert into categoria values(99,'Microprocesadores',91);
insert into categoria values(100,'Modems y redes',91);
insert into categoria values(101,'Monitores',91);
insert into categoria values(102,'Scaners',91);
insert into categoria values(103,'Tarjetas de audio y altavoces',91);
insert into categoria values(104,'Tarjetas de video y sintonizadoras',91);
insert into categoria values(105,'Otros',91);
insert into categoria values(106,'Internet',83);
insert into categoria values(107,'Dominios',106);
insert into categoria values(108,'Otros',106);
insert into categoria values(109,'Ordenadores PC',83);
insert into categoria values(110,'PDA´s',83);
insert into categoria values(111,'Portátiles',83);
insert into categoria values(112,'Software PC',83);
insert into categoria values(113,'Juegos',112);
insert into categoria values(114,'Sistemas operativos',112);
insert into categoria values(115,'Utilidades',112);
insert into categoria values(116,'INMOBILIARIA, HOGAR Y MUEBLES',0);
insert into categoria values(117,'Hogar',116);
insert into categoria values(118,'Artículos de decoración',117);
insert into categoria values(119,'Electrodomésticos',117);
insert into categoria values(120,'Muebles',117);
insert into categoria values(121,'Porcelana, loza y cristalería',117);
insert into categoria values(122,'Inmobiliaria',116);
insert into categoria values(123,'Alquiler',122);
insert into categoria values(124,'Compra-venta',122);
insert into categoria values(125,'Oficinas y locales',122);
insert into categoria values(126,'Jardín',116);
insert into categoria values(127,'Herramientas para el jardín',126);
insert into categoria values(128,'Otros',126);
insert into categoria values(129,'Mascotas y animales',116);
insert into categoria values(130,'Acuario',129);
insert into categoria values(131,'Animales',129);
insert into categoria values(132,'JUGUETES, JUEGOS, ARTICULOS PARA NIÑOS',0);
insert into categoria values(133,'Artículos para Niños',132);
insert into categoria values(134,'Relojes Infantiles',132);
insert into categoria values(135,'Otros',133);
insert into categoria values(136,'Juegos',132);
insert into categoria values(137,'Juegos de Mesa',136);
insert into categoria values(138,'Juegos Didácticos',136);
insert into categoria values(139,'Juegos para Niños',136);
insert into categoria values(140,'Otros',136);
insert into categoria values(141,'Juguetes',132);
insert into categoria values(142,'Barbies',141);
insert into categoria values(143,'Furby',141);
insert into categoria values(144,'Juguetes de Construcción',141);
insert into categoria values(145,'Muñecos',141);
insert into categoria values(146,'Peluches',141);
insert into categoria values(147,'Pokémon',141);
insert into categoria values(148,'Star Wars',141);
insert into categoria values(149,'Teletubbies',141);
insert into categoria values(150,'Vehículos',141);
insert into categoria values(151,'Otros',141);
insert into categoria values(152,'Otros',132);
insert into categoria values(153,'LIBROS, COMICS Y REVISTAS',0);
insert into categoria values(154,'Catálogos, Folletos y Publicaciones',153);
insert into categoria values(155,'Comics',153);
insert into categoria values(156,'Adultos',155);
insert into categoria values(157,'Comic Americano',155);
insert into categoria values(158,'Disney',155);
insert into categoria values(159,'Manga',155);
insert into categoria values(160,'Tebeos',155);
insert into categoria values(161,'Libros',153);
insert into categoria values(162,'Arte, Diseño y Fotografía',161);
insert into categoria values(163,'Ciencias Sociales y Humanidades',161);
insert into categoria values(164,'Historia y Geografía',161);
insert into categoria values(165,'Idiomas',161);
insert into categoria values(166,'Infantil',161);
insert into categoria values(167,'Informática',161);
insert into categoria values(168,'Libros Antiguos',161);
insert into categoria values(169,'Libros de texto',161);
insert into categoria values(170,'Literatura y Novela',161);
insert into categoria values(171,'Medicina y Salud',161);
insert into categoria values(172,'Otros',161);
insert into categoria values(173,'Periódicos',153);
insert into categoria values(174,'Nacionales',173);
insert into categoria values(175,'Internacionales',173);
insert into categoria values(176,'Revistas',153);
insert into categoria values(177,'Informática',176);
insert into categoria values(178,'Temáticas',176);
insert into categoria values(179,'Otras',176);
insert into categoria values(180,'MODA, BELLEZA Y COMPLEMENTOS',0);
insert into categoria values(181,'Belleza',180);
insert into categoria values(182,'Otros',181);
insert into categoria values(183,'Bisutería',180);
insert into categoria values(184,'Moda',180);
insert into categoria values(185,'Moda hombre',184);
insert into categoria values(186,'Moda mujer',184);
insert into categoria values(187,'Ropa niño',184);
insert into categoria values(188,'MONEDAS, SELLOS Y POSTALES',0);
insert into categoria values(189,'Billetes',188);
insert into categoria values(190,'Billetes de España',189);
insert into categoria values(191,'Billetes de lotería',189);
insert into categoria values(192,'Billetes del Mundo',189);
insert into categoria values(193,'Monedas',188);
insert into categoria values(194,'Edad Contenporánea',193);
insert into categoria values(195,'Edad Media',193);
insert into categoria values(196,'Edad Moderna',193);
insert into categoria values(197,'Monedas antiguas',193);
insert into categoria values(198,'Monedas extranjeras',193);
insert into categoria values(199,'Medallas, insignias y otros',193);
insert into categoria values(200,'Postales',188);
insert into categoria values(201,'Extranjeras',200);
insert into categoria values(202,'Nacionales',200);
insert into categoria values(203,'Otras',200);
insert into categoria values(204,'Sellos',188);
insert into categoria values(205,'Antiguos',204);
insert into categoria values(206,'Del mundo',204);
insert into categoria values(207,'Otros',204);
insert into categoria values(208,'Sellos de España',204);
insert into categoria values(209,'MUSICA Y PELICULAS',0);
insert into categoria values(210,'Casettes, Minidisc y Otros',209);
insert into categoria values(211,'CD',209);
insert into categoria values(212,'Alternativa',211);
insert into categoria values(213,'Bandas Sonoras',211);
insert into categoria values(214,'Blues y Jazz',211);
insert into categoria values(215,'Clásica',211);
insert into categoria values(216,'Electrónica y dance',211);
insert into categoria values(217,'Hard rock y Heavy Metal',211);
insert into categoria values(218,'Melódica',211);
insert into categoria values(219,'Música española y Flamenco',211);
insert into categoria values(220,'Músicas del mundo',211);
insert into categoria values(221,'Pop-Rock',211);
insert into categoria values(222,'Otros estilos',211);
insert into categoria values(223,'Coleccionismo',209);
insert into categoria values(224,'Música',223);
insert into categoria values(225,'Películas',223);
insert into categoria values(226,'DVD',209);
insert into categoria values(227,'Acción y aventuras',226);
insert into categoria values(228,'Ciencia-Ficción',226);
insert into categoria values(229,'Comedia',226);
insert into categoria values(230,'Drama',226);
insert into categoria values(231,'Infantil y Juvenil',226);
insert into categoria values(232,'Terror y Suspense',226);
insert into categoria values(233,'Otros',226);
insert into categoria values(234,'Instrumentos Musicales',209);
insert into categoria values(235,'Amplificadores',234);
insert into categoria values(236,'Cuerda',234);
insert into categoria values(237,'Percusión',234);
insert into categoria values(238,'Pianos-Teclados-Acordeones',234);
insert into categoria values(239,'Viento',234);
insert into categoria values(240,'Complementos y otros',234);
insert into categoria values(241,'Partituras',209);
insert into categoria values(242,'Videos',209);
insert into categoria values(243,'Beta',242);
insert into categoria values(244,'VHS',242);
insert into categoria values(245,'Vinilos',209);
insert into categoria values(246,'33 RPM',245);
insert into categoria values(247,'45 RPM',245);
insert into categoria values(248,'Otros',245);
insert into categoria values(249,'VIAJES, VEHICULOS Y DEPORTES',0);
insert into categoria values(250,'Deportes',249);
insert into categoria values(251,'Baloncesto',250);
insert into categoria values(252,'Camping',250);
insert into categoria values(253,'Caza y pesca',250);
insert into categoria values(254,'Ciclismo',250);
insert into categoria values(255,'Deportes de invierno',250);
insert into categoria values(256,'Deportes Náuticos',250);
insert into categoria values(257,'Equipos de gimnasia',250);
insert into categoria values(258,'Fútbol',250);
insert into categoria values(259,'Skate y patines (Rollers)',250);
insert into categoria values(260,'Otros',250);
insert into categoria values(261,'Entradas para Eventos',249);
insert into categoria values(262,'Deportivos',261);
insert into categoria values(263,'Otros eventos',261);
insert into categoria values(264,'Vehículos',249);
insert into categoria values(265,'Barcos',264);
insert into categoria values(266,'Bicicletas',264);
insert into categoria values(267,'Coches',264);
insert into categoria values(268,'Motos',264);
insert into categoria values(269,'Viajes',249);
insert into categoria values(270,'Hoteles, apartamentos, etc',269);
insert into categoria values(271,'Otros',269);
insert into categoria values(272,'Viajes organizados',269);
insert into categoria values(273,'VINOS Y LICORES',0);
insert into categoria values(274,'Aguardientes, licores y otros',273);
insert into categoria values(275,'Cognacs',273);
insert into categoria values(276,'Vinos de Rioja',273);
insert into categoria values(277,'Vinos nacionales',273);
insert into categoria values(278,'whiskys',273);
insert into categoria values(279,'MISCELANEA',0);
insert into categoria values(280,'Eróticas',279);
insert into categoria values(281,'Software',280);
insert into categoria values(282,'Videos',280);
insert into categoria values(283,'Esoterismo',279);
insert into categoria values(284,'Accesorios esotéricos',283);
insert into categoria values(285,'Paranormal',283);
insert into categoria values(286,'Tarots y oráculos',283);
insert into categoria values(287,'Otros',279);
