<html>
<head><title> Nueva subasta de DEUSTOBAR.com</title>
<LINK REL="stylesheet" HREF="../css/deusto.css" TYPE="text/css">
</head>
<!--#include file="../inc/utils.inc"-->
<body background="../images/fondo.jpg">
<%
	cabecera "ALTA DE SUBASTAS EN DEUSTO BAZAR.COM"
%>
	<center><table border="0" width="80%">
		

		<tr><td>
			<p class="instr">
			Pasos para o condiciones para dar de alta su subasta:</p>
			<p class="instr">Debe ser un usuario registrado en DEUSTOBAZAR.com para poder vender. Si todavia no lo es,
			puede <a href="../user/registro.html" target="main" class="instr">registrarse ahora</a>. Es muy facil y gratis.</p>

			<p class="instr">Para poder poner a la venta su producto, debe seleccionar una categoria entre las disponibles
			en nuestro bazar, la eleccion correcta de la categoria es importante para que los usuarios interesados
			puedan encontrar su producto facilmente.</p>
			   
			<p class="instr">Seleccionada la categoria, usted debera rellenar el formulario de venta, en la que debera
			especificar claramente todos los datos del producto, cuanto mas claramente los indique, mayor sera 
			la probabilidad de exito en su subasta</p>
		     </td>
		</tr>
		<tr><td>&nbsp</td></tr><tr><td>&nbsp</td></tr>
		<tr>
			<td align="center"><a href="cats.asp">Comenzar alta</a>
			
			</td>
		</tr>
		

	</table></center>
</body>
</html>